name: protein_scoring
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.8
  - pandas~=1.3.5
  - biopython~=1.79
  - jupyterlab~=3.3.4
  - seaborn~=0.11.2
  - pip
  - scipy~=1.7.3
  - scikit-learn~=1.2.1
  - ete3~=3.1.2
  - pyqt~=5.9.2